# Generated by Django 5.1.5 on 2025-01-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matchifyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otptoken',
            old_name='tp_created_at',
            new_name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(max_length=6),
        ),
    ]
